// Generated by delombok at Mon Aug 26 04:09:54 EDT 2024
/*
 * Table Wrapper CSV Impl
 * Copyright (C) 2022  Spacious Team <spacious-team@ya.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.spacious_team.table_wrapper.csv;

import org.spacious_team.table_wrapper.api.AbstractTableCell;
import java.util.Objects;
import static lombok.AccessLevel.PACKAGE;

public class CsvTableCell extends AbstractTableCell<CsvTableCell.RowAndIndex> {
    private final RowAndIndex rowAndIndex;

    public static CsvTableCell of(String[] row, int columnIndex) {
        return new CsvTableCell(new RowAndIndex(row, columnIndex));
    }

    public CsvTableCell(RowAndIndex rowAndIndex) {
        super(rowAndIndex, CsvCellDataAccessObject.INSTANCE);
        this.rowAndIndex = rowAndIndex;
    }

    @Override
    public int getColumnIndex() {
        return rowAndIndex.getColumnIndex();
    }


    static final class RowAndIndex {
        private final String[] row;
        private final int columnIndex;

        String getValue() {
            return checkIndex() ? row[columnIndex] : null;
        }

        private boolean checkIndex() {
            return columnIndex >= 0 && columnIndex < row.length;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == this) {
                return true;
            } else if (!(obj instanceof RowAndIndex)) {
                return false;
            }
            RowAndIndex other = (RowAndIndex) obj;
            return checkIndex() && other.checkIndex() && Objects.equals(getValue(), other.getValue());
        }

        @Override
        public int hashCode() {
            return Objects.hashCode(getValue());
        }

        
        public RowAndIndex(final String[] row, final int columnIndex) {
            this.row = row;
            this.columnIndex = columnIndex;
        }

        
        public int getColumnIndex() {
            return this.columnIndex;
        }
    }

    @java.lang.Override
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CsvTableCell)) return false;
        final CsvTableCell other = (CsvTableCell) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$rowAndIndex = this.getRowAndIndex();
        final java.lang.Object other$rowAndIndex = other.getRowAndIndex();
        if (this$rowAndIndex == null ? other$rowAndIndex != null : !this$rowAndIndex.equals(other$rowAndIndex)) return false;
        return true;
    }

    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CsvTableCell;
    }

    @java.lang.Override
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $rowAndIndex = this.getRowAndIndex();
        result = result * PRIME + ($rowAndIndex == null ? 43 : $rowAndIndex.hashCode());
        return result;
    }

    
    RowAndIndex getRowAndIndex() {
        return this.rowAndIndex;
    }
}
