// Generated by delombok at Tue Aug 20 15:02:38 EDT 2024
/*
 * Table Wrapper API
 * Copyright (C) 2020  Spacious Team <spacious-team@ya.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.spacious_team.table_wrapper.api;

import java.util.Arrays;

public class AnyOfTableColumn implements TableColumn {

    private final TableColumn[] columns;

    public static TableColumn of(TableColumn... columns) {
        return new AnyOfTableColumn(columns);
    }

    @Override
    public int getColumnIndex(int firstColumnForSearch, ReportPageRow... headerRows) {
        for (TableColumn c : columns) {
            try {
                return c.getColumnIndex(firstColumnForSearch, headerRows);
            } catch (RuntimeException ignore) {
            }
        }
        throw new RuntimeException("Не обнаружен заголовок таблицы, включающий: " + String.join(", ", Arrays.stream(columns).map(TableColumn::toString).toArray(String[]::new)));
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AnyOfTableColumn(columns=" + java.util.Arrays.deepToString(this.columns) + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof AnyOfTableColumn))
            return false;
        final AnyOfTableColumn other = (AnyOfTableColumn) o;
        if (!other.canEqual((java.lang.Object) this))
            return false;
        if (!java.util.Arrays.deepEquals(this.columns, other.columns))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AnyOfTableColumn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + java.util.Arrays.deepHashCode(this.columns);
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public AnyOfTableColumn(final TableColumn[] columns) {
        this.columns = columns;
    }
}
