// Generated by delombok at Tue Aug 20 15:02:38 EDT 2024
/*
 * Table Wrapper API
 * Copyright (C) 2020  Spacious Team <spacious-team@ya.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.spacious_team.table_wrapper.api;

/**
 * Zero-based table cell range
 */
@org.checkerframework.framework.qual.AnnotatedFor("org.checkerframework.checker.nullness.NullnessChecker")
public class TableCellRange {

    public static final @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange EMPTY_RANGE = new EmptyTableCellRange();

    private final int firstRow;

    private final int lastRow;

    private final int firstColumn;

    private final int lastColumn;

    @org.checkerframework.dataflow.qual.Pure
    public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean contains(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellAddress address) {
        return containsRow(address.getRow()) && containsColumn(address.getColumn());
    }

    @org.checkerframework.dataflow.qual.Pure
    public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean containsRow( @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int row) {
        return firstColumn <= row && row <= lastRow;
    }

    @org.checkerframework.dataflow.qual.Pure
    public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean containsColumn( @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int column) {
        return firstColumn <= column && column <= lastColumn;
    }

    /**
     * Adds rows without range check. First rows index of range may become negative.
     * @param number positive or negative values
     */
    @org.checkerframework.dataflow.qual.Pure
    public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addRowsToTop( @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
        return new TableCellRange(firstRow - number, lastRow, firstColumn, lastColumn);
    }

    /**
     * @param number positive or negative values
     */
    @org.checkerframework.dataflow.qual.Pure
    public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addRowsToBottom( @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
        return new TableCellRange(firstRow, lastRow + number, firstColumn, lastColumn);
    }

    /**
     * Adds columns without range check. First column index of range may become negative.
     * @param number positive or negative values
     */
    @org.checkerframework.dataflow.qual.Pure
    public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addColumnsToLeft(int number) {
        return new TableCellRange(firstRow, lastRow, firstColumn - number, lastColumn);
    }

    /**
     * @param number positive or negative values
     */
    @org.checkerframework.dataflow.qual.Pure
    public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addColumnsToRight(int number) {
        return new TableCellRange(firstRow, lastRow, firstColumn, lastColumn + number);
    }

    private static class EmptyTableCellRange extends TableCellRange {

        @org.checkerframework.dataflow.qual.SideEffectFree
        private EmptyTableCellRange() {
            super(0, 0, 0, 0);
        }

        @org.checkerframework.dataflow.qual.Pure
        public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean contains(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this, @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellAddress address) {
            return false;
        }

        @org.checkerframework.dataflow.qual.Pure
        public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean containsRow(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int row) {
            return false;
        }

        @org.checkerframework.dataflow.qual.Pure
        public  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull boolean containsColumn(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int column) {
            return false;
        }

        @org.checkerframework.dataflow.qual.Pure
        public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addRowsToTop(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
            return this;
        }

        @org.checkerframework.dataflow.qual.Pure
        public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addRowsToBottom(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
            return this;
        }

        @org.checkerframework.dataflow.qual.Pure
        public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addColumnsToLeft(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
            return this;
        }

        @org.checkerframework.dataflow.qual.Pure
        public @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull TableCellRange addColumnsToRight(@org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull EmptyTableCellRange this,  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int number) {
            return this;
        }
    }

    @org.checkerframework.dataflow.qual.Pure
    public int getFirstRow() {
        return this.firstRow;
    }

    @org.checkerframework.dataflow.qual.Pure
    public int getLastRow() {
        return this.lastRow;
    }

    @org.checkerframework.dataflow.qual.Pure
    public int getFirstColumn() {
        return this.firstColumn;
    }

    @org.checkerframework.dataflow.qual.Pure
    public int getLastColumn() {
        return this.lastColumn;
    }

    @org.checkerframework.dataflow.qual.Pure
    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof TableCellRange))
            return false;
        final TableCellRange other = (TableCellRange) o;
        if (!other.canEqual((java.lang.Object) this))
            return false;
        if (this.getFirstRow() != other.getFirstRow())
            return false;
        if (this.getLastRow() != other.getLastRow())
            return false;
        if (this.getFirstColumn() != other.getFirstColumn())
            return false;
        if (this.getLastColumn() != other.getLastColumn())
            return false;
        return true;
    }

    @org.checkerframework.dataflow.qual.Pure
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TableCellRange;
    }

    @org.checkerframework.dataflow.qual.Pure
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getFirstRow();
        result = result * PRIME + this.getLastRow();
        result = result * PRIME + this.getFirstColumn();
        result = result * PRIME + this.getLastColumn();
        return result;
    }

    @org.checkerframework.dataflow.qual.Pure
    public java.lang.String toString() {
        return "TableCellRange(firstRow=" + this.getFirstRow() + ", lastRow=" + this.getLastRow() + ", firstColumn=" + this.getFirstColumn() + ", lastColumn=" + this.getLastColumn() + ")";
    }

    @org.checkerframework.dataflow.qual.SideEffectFree
    public TableCellRange(final  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int firstRow, final  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int lastRow, final  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int firstColumn, final  @org.checkerframework.checker.initialization.qual.Initialized @org.checkerframework.checker.nullness.qual.NonNull int lastColumn) {
        this.firstRow = firstRow;
        this.lastRow = lastRow;
        this.firstColumn = firstColumn;
        this.lastColumn = lastColumn;
    }
}
